mysageone_uk:
  database_name: 'sageone_mso_uk'
  username: 'nigel'
  password: 'password'
  yml_location: 'host_app/config/database.yml'
  bitflag: 1
sage_one_advanced:
  database_name: 'sageone_acc_uk'
  username: 'nigel'
  password: 'password'
  yml_location: 'host_app/config/database.yml'
  bitflag: 2
new_accountant_edition:
  database_name: 'accountants_uk'
  username: 'nigel'
  password: 'password'
  yml_location: 'host_app/config/database.yml'
  bitflag: 4
chorizo:
  database_name: 'sageone_collaborate_uk'
  username: 'nigel'
  password: 'password'
  yml_location: 'host_app/config/database.yml'
  bitflag: 8
sage_one_accounts_uk:
  database_name: 'sageone_acc_uk'
  username: 'nigel'
  password: 'password'
  yml_location: 'host_app/config/database.yml'
  bitflag: 16
sage_one_addons_uk:
  database_name: 'sageone_addons_uk'
  username: 'nigel'
  password: 'password'
  yml_location: 'host_app/config/database.yml'
  bitflag: 32
